fix: Incorrect service lifetimes for controller resolution
buehler/dotnet-operator-sdk pull request #455
Opened 2022-06-20 20:53 UTC by erin-allison

This resolves #450, confirmed by @rcm-steve-horne.

The bulk of the change is constructing a lifetime scope around each `IManagedResourceController`.

2022-06-23 09:14 UTC, buehler approved these changes

2022-06-23 09:16 UTC, buehler requested changes
Just found out that the linter / compilation complains about non awaited calls

2022-06-23 09:16 UTC, buehler commented on src/KubeOps/Operator/Controller/ResourceControllerManager.cs
> +            scopedController.StopAsync();
You'll need to await this call

2022-06-23 09:16 UTC, buehler commented on src/KubeOps/Operator/Controller/ResourceControllerManager.cs
> +                scopedController.StartAsync();
await as well

2022-06-23 09:16 UTC, buehler commented on src/KubeOps/Operator/Controller/ResourceControllerManager.cs
> +                scopedController.StopAsync();
await as well

2022-06-23 13:24 UTC, erin-allison commented
Yeah I saw that but those were non-awaited beforehand too.

2022-06-23 14:30 UTC, erin-allison commented
I'll look at those changes later tonight - I was avoiding making those changes because I'll have to do some trickery to get the IObservable to properly call an async method without just call-and-ignore, which is a bad pattern to introduce.

2022-08-09 15:19 UTC, buehler commented
hey @erin-allison 
It has been some time since I last reviewed this. What was/is the reason that all registrars and other stuff is now transient? Does that not introduce errors when event queues are instantiated twice?

2022-08-09 16:27 UTC, erin-allison commented
> hey @erin-allison It has been some time since I last reviewed this. What was/is the reason that all registrars and other stuff is now transient? Does that not introduce errors when event queues are instantiated twice?

Been a bit for me too. Can you clarify a bit on which components you're referring to? The registrar is a singleton and nothing here changes that. The changes in this issue are centered around encapsulating a lifetime scope around the resource controllers so they can resolve scoped services, as they were originally resolving from the root service provider.

2022-08-10 07:55 UTC, closed without merging