feat(core): Use built-in libraries for X509 Certificates
buehler/dotnet-operator-sdk pull request #756
Opened 2024-05-08 06:46 UTC by ian-buse

Hey there @buehler!

This PR adds a new CertificateGenerator to Operator.Web, and it reworks a handful of the classes in Operator.Web to support using certificates in code. I more or less re-implemented the BouncyCastle solution from the CLI in Operator.Web using the built-in .NET classes, and I went to some length to ensure the generated certificates are virtually identical to those produced by BouncyCastle.

As for the reasoning, I admittedly had some trouble getting LocalTunnel working reliably in my environment. My company prefers just using our internal network versus a service, but I wanted to have a easy way to use self-signed certs with Kestrel and using your nifty webhook generator methods that are in the `DevelopmentTunnelService`. It also requires some knowledge of certificates and keys to get the BouncyCastle library working with certain .NET methods/classes, so this was a bit of a usability barrier for those who are unfamiliar.

Here are the changes I've made:
- Pulled the webhook generator methods into a base class. The base class is implemented by `TunnelWebhookService` and `CertificateWebhookService`. The new `CertificateWebhookService` is added to the operator with a new method in `OperatorBuilderExtensions`, called `UseCertificateProvider()`.
  - Moved or renamed a couple of classes to support this (`TunnelConfig` -> `WebhookConfig`, `WebhookLoader` moved).
- Created a new `CertificateGenerator` class in Operator.Web.
  - Added some supporting extension methods.
  - The `CertificateGenerator` implements an interface called `ICertificateProvider`, which is used by `UseCertificateProvider()` so someone can implement their own solution (like reading from a file) if they want.
- I replaced BouncyCastle in the CLI with the Operator.Web generator in 3bb58fb.
- I added a few tests in ce7a7b5.

There are no breaking changes with these commits. 

Regards,

Ian

2024-05-10 09:22 UTC, buehler commented
Hey @ian-buse 

Thank you for your contribution! :-)

Yes, certificate stuff is quite weird, and you need a lot of time to get your head around it. The way these certificates are implemented now is to ensure that webservers do not reject them because they all need certain custom extensions.

I had the same issues with localtunnel not being reliable. I'll review it right away :-)

2024-05-10 17:58 UTC, ian-buse commented
Thanks for taking a look at it. I just realized I made a small mistake with the EnhancedKeyUsageExtension critical = true. Easy fix but I wanted to point it out, I can add it to the PR.

2024-05-13 09:26 UTC, buehler requested changes
Hey @ian-buse 

Thanks again for the contribution!

The linter is not happy right now with something (thus, the build is failing).

A made a few comments that I'd like to discuss.

One thing about the reason: if I understand you correctly, you had problems with local tunnel being shakey (like I did). Now you implemented a special way to use self signed certificates for local development without localtunnel.

I really do like the idea! Since I had the same issues with localtunnel, I'd go even further and say we remove localtunnel altogether and make a breaking change. Then local webhooks can and should be tested with a local kubernetes instance (mini kube or whatever). What do you think about this?

I don't even know if this local tunnel feature was used heavily.

And another question: why did you replace bouncycastle? (I'm curious)

2024-05-13 09:26 UTC, buehler commented on src/KubeOps.Operator.Web/Certificates/CertificateExtensions.cs
> +        public static byte[] EncodeToPemBytes(this X509Certificate2 certificate) => Encoding.ASCII.GetBytes(certificate.EncodeToPem());
would UTF8 be better in this case?

2024-05-13 09:26 UTC, buehler commented on src/KubeOps.Operator.Web/Certificates/CertificateGenerator.cs
> +        private (X509Certificate2 Certificate, AsymmetricAlgorithm Key) _server;
instead of using a private field and init them in the public properties, you could use `Lazy` to init them when you access the value and then use the property to access the values.

2024-05-13 09:26 UTC, buehler commented on src/KubeOps.Operator.Web/Certificates/CertificateGenerator.cs
> +        private (X509Certificate2 Certificate, AsymmetricAlgorithm Key) _server;
(this would also simplify the dispose function)

2024-05-13 09:26 UTC, buehler commented on src/KubeOps.Operator.Web/Certificates/CertificateGenerator.cs
> +        private sealed class CustomX509AuthorityKeyIdentifierExtension(X509Certificate2 certificate, bool critical)
nice :)

but if the code is shipped with .net7 and further, could we use a compiler directive here to only add the code when used with net6? reasoning: security updates whatsoever would be provided by ms directly.

2024-05-13 09:26 UTC, buehler commented on src/KubeOps.Operator.Web/Certificates/ICertificateProvider.cs
> +    public interface ICertificateProvider : IDisposable
this should be moved into abstractions (interface)

2024-05-13 16:41 UTC, ian-buse commented on src/KubeOps.Operator.Web/Certificates/CertificateExtensions.cs
> +        public static byte[] EncodeToPemBytes(this X509Certificate2 certificate) => Encoding.ASCII.GetBytes(certificate.EncodeToPem());
Yeah I think so. I believe PEM is (traditionally) encoded in ASCII, but YAML is usually UTF-8 and this is being sent as part of the YAML for the webhooks.

2024-05-13 16:43 UTC, ian-buse commented on src/KubeOps.Operator.Web/Certificates/CertificateGenerator.cs
> +        private (X509Certificate2 Certificate, AsymmetricAlgorithm Key) _server;
Okay, I will look into doing this. Thanks.

2024-05-13 16:46 UTC, ian-buse commented on src/KubeOps.Operator.Web/Certificates/CertificateGenerator.cs
> +        private sealed class CustomX509AuthorityKeyIdentifierExtension(X509Certificate2 certificate, bool critical)
Yeah absolutely we can do that. Did you have any plans for dropping .NET 6 support when LTS ends in November?

2024-05-13 18:08 UTC, ian-buse commented
> Hey @ian-buse
> 
> Thanks again for the contribution!
> 
> The linter is not happy right now with something (thus, the build is failing).
> 
> A made a few comments that I'd like to discuss.
> 
> One thing about the reason: if I understand you correctly, you had problems with local tunnel being shakey (like I did). Now you implemented a special way to use self signed certificates for local development without localtunnel.
> 
> I really do like the idea! Since I had the same issues with localtunnel, I'd go even further and say we remove localtunnel altogether and make a breaking change. Then local webhooks can and should be tested with a local kubernetes instance (mini kube or whatever). What do you think about this?
> 
> I don't even know if this local tunnel feature was used heavily.
> 
> And another question: why did you replace bouncycastle? (I'm curious)

Yeah, I had problems with LocalTunnel not working correctly, which made me implement the self-signed certs instead. Removing LocalTunnel would be fine with me!

BouncyCastle is a great library, but I replaced BouncyCastle with `System.Security.Cryptography` for a few reasons:

- It is easier to use with .NET classes that use certificates. For example, I can configure Kestrel like so:

    ```csharp
    using CertificateGenerator generator = new(ip);
    using X509Certificate2 cert = generator.Server.CopyServerCertWithPrivateKey();
    builder.WebHost.ConfigureKestrel(serverOptions =>
    {
        serverOptions.Listen(IPAddress.Any, 443, listenOptions =>
        {
            // If you used BouncyCastle, you would have to convert the 
            // BouncyCastle cert to X509Certificate2 before using it
            listenOptions.UseHttps(serverCert);
        });
    });
    ```

- Everything that is being done with BouncyCastle in `KubeOps.Cli` can be done with `System.Security.Cryptography`, meaning I don't think the dependency is needed. Also, some organizations would prefer the operator use the built-in .NET library over a 3rd-party library when dealing with security. I've seen other projects also moving this direction for the same reasons (web-push-libs/web-push-csharp/pull/75, planetarium/libplanet/issues/66)
- `System.Security.Cryptography` uses native DLLs and it is probably faster, though I haven't tested it myself.

I'll work on resolving the linter problem and other things you brought up. 😊

-Ian

2024-05-13 19:12 UTC, buehler commented on src/KubeOps.Operator.Web/Certificates/CertificateGenerator.cs
> +        private sealed class CustomX509AuthorityKeyIdentifierExtension(X509Certificate2 certificate, bool critical)
Oh wow, good call. Actually, I never had it on the radar. Well, then we can let it slip and drop it in November.

2024-05-13 19:34 UTC, buehler commented
Thanks for the explanation :-)

Yeah, I can absolutely understand that. I think more or less the same way, but BouncyCastle is (sometimes) great because the abstract the weird stuff like "OiD(183459122)" with something that has a meaning. That was the main reason.

I do like the move! Especially because of the native libs.

Regarding the removal of localtunnel: wdyt about this: you mark it as "deprecated" with the compiler attribute and we remove it in a later stage.

and regarding the "lazy" thing, I just tried it with the following example:
```csharp
global using CertificatePair =
    (System.Security.Cryptography.X509Certificates.X509Certificate2 Certificate,
    System.Security.Cryptography.AsymmetricAlgorithm Key);

internal class CertificateGenerator : IDisposable
{
    public Lazy<CertificatePair> Root => new(Generate);

    private CertificatePair Generate()
    {
        return default;
    }

    public void Dispose()
    {
        if (Root.IsValueCreated)
        {
            Root.Value.Certificate.Dispose();
            Root.Value.Key.Dispose();
        }
    }
}
```

What do you think about such an implementation? (just a suggestion)

2024-05-14 01:27 UTC, ian-buse commented
> Thanks for the explanation :-)
> 
> Yeah, I can absolutely understand that. I think more or less the same way, but BouncyCastle is (sometimes) great because the abstract the weird stuff like "OiD(183459122)" with something that has a meaning. That was the main reason.
> 
> I do like the move! Especially because of the native libs.
> 
> Regarding the removal of localtunnel: wdyt about this: you mark it as "deprecated" with the compiler attribute and we remove it in a later stage.
> 
> and regarding the "lazy" thing, I just tried it with the following example:
> 
> ```cs
> global using CertificatePair =
>     (System.Security.Cryptography.X509Certificates.X509Certificate2 Certificate,
>     System.Security.Cryptography.AsymmetricAlgorithm Key);
> 
> internal class CertificateGenerator : IDisposable
> {
>     public Lazy<CertificatePair> Root => new(Generate);
> 
>     private CertificatePair Generate()
>     {
>         return default;
>     }
> 
>     public void Dispose()
>     {
>         if (Root.IsValueCreated)
>         {
>             Root.Value.Certificate.Dispose();
>             Root.Value.Key.Dispose();
>         }
>     }
> }
> ```
> 
> What do you think about such an implementation? (just a suggestion)

Good, I'm glad you like the changes! I've resolved most of the issues we talked about, including the UTF-8 encoding, linting issues, moving `ICertificateProvider` to `KubeOps.Abstractions`, and deprecating LocalTunnel. 

I like the idea of using Lazy, and I implemented a variation of your code in the latest commit. This cleaned up the interface implementation a lot. We still needed to use a backing field, otherwise the certificate will regenerate every time the property is accessed, so I followed [this Microsoft doc](https://learn.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization#implementing-a-lazy-initialized-property) for how to do it.

2024-05-14 03:47 UTC, ian-buse commented on src/KubeOps.Operator.Web/Certificates/ICertificateProvider.cs
> +    public interface ICertificateProvider : IDisposable
This has been moved to KubeOps.Abstractions.

2024-05-14 03:47 UTC, ian-buse commented on src/KubeOps.Operator.Web/Certificates/CertificateExtensions.cs
> +        public static byte[] EncodeToPemBytes(this X509Certificate2 certificate) => Encoding.ASCII.GetBytes(certificate.EncodeToPem());
Done!

2024-05-14 04:00 UTC, ian-buse commented on src/KubeOps.Operator.Web/Certificates/CertificateGenerator.cs
> +        private (X509Certificate2 Certificate, AsymmetricAlgorithm Key) _server;
I put this in using a private field `Lazy<CertificatePair>` backing the public property `CertificatePair`.

2024-05-15 07:24 UTC, buehler approved these changes
Very cool :)

Just realized that the local tunnel stuff already was in "preview". As such, we can remove it later on without having a breaking change.

2024-05-15 07:31 UTC, merged